// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iomavnsblxiyrcflnvir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvbWF2bnNibHhpeXJjZmxudmlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwOTg4MjYsImV4cCI6MjA1NzY3NDgyNn0.sDaaS2rCtimS4sP3bYdVGa4dA1u3KtkLHK1DzCrl6Sg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);